### ISSUE TITLE
where to set datapath

### ISSUE THREAD

**Issue by floswald** [justinenayral/ACE_Traeger_replication.jl#5]
where do I have to do that?

## Datapath
To output some certain figures, the data provided in the original replication package is needed. The specific packages necessary are given below.
The user needs to save the data in datapath:
```julia
datapath = "C:/Users/..."
```

**Comment by norbertmonti** [comment]
Here are step-by-step instructions:

1. Save replication data (.mat files) in any folder of your choice. For example, I created the following folder and saved my data here: "C:\Users\Guada\Documents\Test\data". 
2. Then, create a variable mydatapath. In my case this is mydatapath = "C:\Users\Guada\Documents\Test\data". Your path will likely slightly differ.
3. Then create a variable specifying where you want your output saved. In my case this is mypath = "C:\Users\Guada\Documents\Test\output". 
4. Then run your function, for example ACE_Traeger_replication.Impulse_response_combined(mypath, 
mydatapath)

Let us know if this solves the issue, if not, we are happy to provide further instructions.

**Comment by justinenayral** [comment]
Just define where your data are stored in datapath by running in the julia repl, prior to run the functions. 
datapath = "C:/Users/..." 
Replace  "C:/Users/..."  by the path where your data are stored. 
Then, for all the other functions, just give as an argument datapath when this is needed.  
For instance in ACE_Traeger_replication.TempFitSim(path, datapath), if your datapath is previously defined it should work. 

Do the same thing for path (i.e. your working directory).

We did not include the data in the package because we were not allowed to do so by the authors of the original paper.
